language: ruby
script: "bundle && bundle install && bundle exec rake test:units"
sudo: false
cache: bundler

rvm:
- 2.5
- 2.4
- 2.3
- 2.2
- 2.1
- 2.0
- 1.9

gemfile:
- Gemfile

matrix:
  exclude:
    - rvm: 1.9
      gemfile: Gemfile.rails5
    - rvm: 2.1
      gemfile: Gemfile.rails5
    - rvm: 2.0
      gemfile: Gemfile.rails5
